#!/bin/bash -l

#SBATCH --job-name=iso_Blanco1
#SBATCH --output=iso_Blanco1.out
#SBATCH --partition=defq
#SBATCH --time 03-00:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=12
#SBATCH --mem-per-cpu=16GB

#SBATCH --mail-type=ALL
#SBATCH --mail-user=kding5@jhu.edu

#SBATCH --export=ALL

python main_mp.py
