#!/bin/bash -l

#SBATCH --job-name=iso_alphaPer
#SBATCH –output=”iso_alphaPer.out”
#SBATCH –partition=defq
#SBATCH —t 03-00:00:00
#SBATCH –nodes=1
#SBATCH –ntasks-per-node=5
#SBATCH –mem-per-cpu=16GB

#SBATCH –account=kding5
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kding5@jhu.edu

#SBATCH –export=ALL

python main.py
