#!/bin/bash -l

#SBATCH --job-name=iso_Praesepe
#SBATCH --partition=defq
#SBATCH --array=0-19
#SBATCH --time 03-00:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=20GB
#SBATCH --output=iso_Praesepe_%a.out

#SBATCH --mail-type=ALL
#SBATCH --mail-user=kding5@jhu.edu

#SBATCH --export=ALL

echo "SLURM_JOBID: " $SLURM_JOBID
echo "SLURM_ARRAY_TASK_ID: " $SLURM_ARRAY_TASK_ID
echo "SLURM_ARRAY_JOB_ID: " $SLURM_ARRAY_JOB_ID

python main.py $SLURM_ARRAY_TASK_ID
