#!/bin/bash -l

#SBATCH --job-name=iso_Praesepe
#SBATCH --output=iso_Praesepe.out
#SBATCH --partition=defq
#SBATCH --time 03-00:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=10
#SBATCH --mem-per-cpu=20GB

#SBATCH --mail-type=ALL
#SBATCH --mail-user=kding5@jhu.edu

#SBATCH --export=ALL

python main_mp.py
